
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 11 15:11:52 GMT 2015
//----------------------------------------------------

package Parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DISPLAY = 2;
  public static final int DIVIDE = 23;
  public static final int LKEY = 35;
  public static final int LBRACKET = 33;
  public static final int LPAREN = 30;
  public static final int INT = 11;
  public static final int LESS = 28;
  public static final int MINUS = 21;
  public static final int STATIC = 5;
  public static final int RPAREN = 31;
  public static final int SEMICOLON = 32;
  public static final int AND = 24;
  public static final int OR = 25;
  public static final int COMMA = 38;
  public static final int CLASS = 4;
  public static final int MAJOR = 29;
  public static final int PLUS = 19;
  public static final int MAIN = 7;
  public static final int IF = 12;
  public static final int THIS = 17;
  public static final int EOF = 0;
  public static final int RETURN = 10;
  public static final int RBRACKET = 34;
  public static final int RKEY = 36;
  public static final int NEW = 18;
  public static final int error = 1;
  public static final int DISTINCT = 27;
  public static final int LITERALINT = 40;
  public static final int BECOMES = 20;
  public static final int VOID = 6;
  public static final int TIMES = 22;
  public static final int ELSE = 13;
  public static final int POINT = 37;
  public static final int WHILE = 14;
  public static final int PUBLIC = 3;
  public static final int EXTENDS = 9;
  public static final int SYSTEMOUTPRINTLN = 15;
  public static final int STRING = 8;
  public static final int DBECOMES = 26;
  public static final int LENGTH = 16;
  public static final int IDENTIFIER = 39;
}

